version: 2.1
workflows:
  build-test:
    jobs:
      - build-py
      - build-js
      - check-black
      - mypy
      - pytest

jobs:
  build-py:
    docker:
      - image: circleci/python:3.9.2
    steps:
      - checkout
      - run:
# libasound2-dev for building python-rtmidi package
# libjack-jackd2-dev, libsndfile1, swig for building amio package
          command: |
            sudo apt-get -y install libasound2-dev libjack-jackd2-dev libsndfile1 swig
            poetry install --no-ansi
            poetry build

  build-js:
    docker:
      - image: cimg/node:14.16.0
    steps:
      - checkout
      - run:
          command: (cd manokee/web/front && npm install && npx prettier --check . && npm run build)

  mypy:
    docker:
      - image: circleci/python:3.9.2
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get -y install libasound2-dev libjack-jackd2-dev libsndfile1 swig
            poetry install --no-ansi
            poetry run mypy manokee/

  check-black:
    docker:
      - image: cimg/python:3.9.2
    steps:
      - checkout
      - run:
          command: |
            pip install black
            black --check .

  pytest:
    docker:
      - image: circleci/python:3.9.2
    steps:
      - checkout
      - run:
          command: |
            sudo apt-get -y install libasound2-dev libjack-jackd2-dev libsndfile1 swig
            poetry install --no-ansi
            poetry run coverage run --source manokee -m pytest
            poetry run coverage report -m
            poetry run coverage html
      - store_artifacts:
          path: htmlcov

